sudo: required
language: go
services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.17.1
  - secure: j/tMg8ROJWqJ482ebiy6FpNeSPMTlCkZFKeVqJpo5ek4qBHk36e7ggOyAgZiQMcsg0b8Ihyvyr1SAhbiahbS5+JTBIkZppSdABECtbTmm4L5Sql8s70UsmwZgWh6VsrVmjKHeFLB431b+aZIxh8zRmjszhsFXL1EFnAOyvzRCDqU5Qb/5QNSSK+t/LZ44y7C3ey3TopBz/oFYtrLq39J1gGDUR4r9IMHM5COXaWcm9iPYg3uG4yr4R/3h0ElunPy3tjY1dyEsWInjVxbzrdNOtsUbjgOiyT8nnsElJGNJSLL2l2XNEdQK3Lwp8wXxJ4KwSq5m4oecV6tEz8LwKptZR/LH/6nxvAG7GkONqzafqN3z2VqV1wMyN7WGG2t7uv01D/93MrXY8QvBmM543qH4GwhEwhUvZ30Kizg5jbSht1TkuocBDuOa/dam7Ul7HD/k3CruHsIpy2qenZYLzzeplBPBhtcElH0oSr/h5A8kW2WZrqSnV14hbMJPWLweS104TRCso8PjH5qKDO2cqzlt7ziqqHChls7yqyv/P3PjCHgQTvTs9VKEEctE7ASvj37nGQVm+wjmWDBV99deoBI8QFRGozcrwkqgrLQmCbB+jodRfNZBzs60RAP12eDqWHrBo9gX7/X9vLu6iTM6Qv6ErJ2bUVfukkhrYlyALxEuWA=
  - secure: LV3fHn67qgXoUEAuZ2MEsgYAHKpKEi07iIyOlPGN8YCYQY1zvtyvgpPmAWPZxvA0iW5sqIJswZ6E2es9CJJQo6bEm2rybhcmChqeOO8hyWhoOwAGa5rddfCCi7DR4cELwjAdFZkXHhkm2tBqsuFTJgxg1SjGMQpNsa45ANr/5r3BXRaXEJ7O7P+ubpoYosRLyZ7Yw2uA02a+dF3GzR7YhqplM9vehIdDkwTQtwK/voCNsqUKMBIPc8lSdxawTIrVeZT3KldUAzK6NZzqHZHZuLE9NJWftwnN2NdO6T/95dj7l5xV9xWqcGBxKh0rb0D4PbzABOKhk6DrQcrqd3HGJThD6SNcVK1i52FRVE/2CmDCRBKdXzuCoJy982QoqhJ7n0SLgXgs6N+iFWEVKhzlstbl0gxT+qf8IK7jNfajuOyRDqZeYLcEB6JULqYezrBj34k+KkTd6SfBBp0UzcYmLWyxZufQxlR8xRP71IVG+1N8NF4TuTX/KFHQ79BTkSD7yIEnEXq1+8R7u0fB8g0+qMvPY/EFpXgveEUludisi6rTJ3UnGnnORm9ap4vvxQ8aIdbOva8LwAbDXjZoK5QgokfFs2J0bp0ulvB4T3wY5ndFZO8ahYyEXbm9bwqwnMuYeDgb6wqQLonCz3EblCv0BAm7LVs9jXl/L9hmMZOZ+TA=
  matrix:
  - secure: gmPQBxdJrMvpevkKjoGa51ihcZIBq6PkTwWobQk5ZSebHI36EFJT6WRJvvjEj2YwGyZplRfh3/L/HZMxanRMEHQYZ19TpvsZylReNpVWVFFXTLGn5R+lQeGujwY4JhchxUslMuxBqqpDKdULCfYx4EGwkLuLEaWVRI4tTJ7b5ZsDgqUS26e6N3mNxPVMeb8DBIShYEEUOn/fSfx8DNmc7YRm4mbwQFkm7MoWghXU2PaV/+95eAIJH8swa/l8OsaxLTGyui9oqAw2dYKkVPRZ3e93PbNBP2Y6ZYcm0qdgk1e3qKwi5wR4zz7l/4V7TYQ61GndxrqwiLGpRrSzAEh0JFfZB5V+H/zB3NYceF6aD/fwSD0fr+MPLFhtWLbwPWGEabviCEktOa/CS+TXzy1R3XB00Iwavt8CBJ5OzdirIjr30VoaeWqV16pTo6Z/lQZEzU32jFuL4HdVm0O4kV/6NRpo0ZbIhqGNwqO9pGVywkGVP3kej026fchKxP2YdY4Z+yCh2inwELfBhh5J+dWF0phQenCuIxI7XwuCyR8ASsmTIuUYsLo46B/pJBRX7v9EXJCC/QoPWBjneWYRqs0AJ9Hm4k0yeaMooKGDeU0FWPq4drEDQZXZKEcFG1KWf2JzzsPp62RnXJajUfXjgRP4XXJKNM7EUY/C0tAIn72e9Fo=
  - secure: KFHwolAABe9INaNpfFhckCxgqP0cP+yew8lZw9xBtiCsRqiN3Pzxrv4mU9ORcQTOshHRYWIJWeFUzqVIm72XOvcpmcXhz9VT4/HFOXr1x/eN/GgwYh0IMeyar4HlL+bYTPxza5GeHbN5r0w9TtpXIzG8NDGz+QEorUiM/d2tuMkOH0bPl+JedIs5RLWaFszaQ4FkMe+1vrhddW51kjh931XounGgjikmQ4J0CFErp3kH9Dv9niarn7KKeTNvCaFWWyg0zTIF5ExLuVNjsZTHCH3zrJfnVbZ/kKEpe3VUmK+fXdkhe2brPPiWsjaRRxxXS6kSuUFmXOI04eJf9TDZhL+cjede8279yZ+lQ9/2vP3gzMDV4bUKO7aUfUQvRw3W6MytTusmFKwXCqz90Q8nqwIC8qSR5Qtu2qRKuvWPuIena4v9cuG9cnI8VBosMLj7/CUOObDly1EcePADxjaPZ80R5rD6yzQrKlqZRvLJlIxhBNTQfNNgp6G1jcGfsyp97TrERMsQjqvByX0/O/lMTXoQpb8F9gG14jJRGhrlhFuEjaVoKWNqCVNFhLopZy2iHrluqG2zxKeGQGWKouZrhALN/GK3OBdyE1SK6NGSoirttnZXn69zkYiKp/CcTUPvroFQgMsjWxK+gh6cKZKc3YRESG80ol3Q1QD761EKG/s=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g npm
- node -v && npm -v
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
- docker-compose build
- docker-compose up -d
before_script:
- docker ps
- docker-compose ps
- docker-compose logs
script:
- curl http://localhost/
after_script:
- docker-compose stop
- docker-compose rm -f
notifications:
  emails:
    on_success: never
    on_failure: always
