version: '2'

services:
  app:
    image: node-app:latest
    ports:
      - 3000

  nginx:
    container_name: node-nginx-lb
    build: ./nginx
    links:
      - app:app
    ports:
      - 80:80
    depends_on:
      - app

