version: '3'

services:
  app:
    build: ./app
    ports:
      - 8080
    links:
      - db
    env_file: environment/production.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    restart: always
    env_file: environment/production.env
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  nginx:
    container_name: node-nginx-lb
    build: ./nginx
    restart: always
    links:
      - app:app
    ports:
      - 80:80
    depends_on:
      - app

