version: '2'

services:
  app:
    build: ./app
    ports:
      - 3000
    links:
      - db
    env_file: environment/production.env

  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    restart: always
    env_file: environment/production.env
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  nginx:
    container_name: node-nginx-lb
    build: ./nginx
    links:
      - app:app
    ports:
      - 80:80
    depends_on:
      - app

